#! /bin/sh

# HADOOP NAMENODE AND DIRECTORY SETUP
hadoop namenode -format
start-dfs.sh
start-yarn.sh

hdfs dfs -mkdir -p /user/$(whoami)
hdfs dfs -mkdir -p /tmp
hdfs dfs -mkdir -p /user/hive/warehouse
hdfs dfs -chmod g+w /tmp
hdfs dfs -chmod g+w /user/hive/warehouse

schematool -dbType derby -initSchema